name: Deploy on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
        name: Clone repository
        with:
          repository: "SGmuwa/Web-develop-docker-7-semester"
      - run: mv ./frontend/* ./
        name: Move need files
      - uses: actions/heroku@master
        name: Heroku build
        with:
          args: "container:login"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - uses: actions/heroku@master
        name: Heroku push
        with:
          args: "container:push web"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
      - uses: actions/heroku@master
        name: Heroku deploy
        with:
          args: "container:release web"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
